### ISSUE TITLE
Why parth/v2 in go.mod?

### ISSUE THREAD

**Issue by h2non** [codemodus/parth#2]
You is generating conflicts when depending on the package in non-`go mod` way (Go < 1.11).

Can you make the path consistent to the actual Github path?
`https://github.com/codemodus/parth`

Thanks!

**Comment by daved** [comment]
Thanks for reporting this. Would you, please, provide the steps which result in an error and/or refer to `go mod` documentation which clarifies what needs to be corrected? As far as I understand and have tested, everything works as it should for v1 and v2 releases. Apologies if I'm in error.

**Comment by daved** [comment]
The first problem I found is that the example file package declaration is `package parth_test` which contains the import `github.com/codemodus/parth`. This is creating an indirect dependency for v1.x.x in projects importing parth v2.x.x. The import should, instead, be `github.com/codemodus/parth/v2`. This is now corrected.

The second problem I found, and what I think is the concern here, is that older versions of Go will not import `github.com/codemodus/parth/v2` properly while parth relies solely on tags for versioning. However, I believe that it is reasonable to expect developers to upgrade their Go installs strictly on the basis of security, and since all supported versions of Go can consume tag-versioned Go packages, I don't think it's worth altering the project directory structure.

I'm open to hearing an argument otherwise, but I'll close this until then.
